---
- hosts: localhost
  vars:
    db_password: password
  tasks:
    - name: copy repo file to desired destination.
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: checks to see if server is active.
      become: yes
      apt: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: if it is ON/Enabled.
      become: yes
      systemd: name=mariadb state=started enabled=yes

    - name: something to do with a template in that text file.
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: secure installation
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: pulls it out of the archive.
      unarchive: src=db/db.tgz dest=~/ mode=0000

    - name: creates database using password.
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
