---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: takes file from remote host to local host
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: package manager
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: begins service
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: injects values filling out the info
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: reads file and input
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: tar, opens/uncompressed
      unarchive: src=db/db.tgz dest=~/

    - name: cd to directory, runs ssh cmd, and takes back to directory | ignore all errors
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
