---
- hosts: web
  vars:
   server_name: curriculum
   service_name: curriculum
   service_version: 1.0
   app_key: tf-20161215065557563864500243.cuc0twrqljlf.us-west-2.rds.amazonaws.com
   app_env: test
   db_host: localhost
   db_database: curriculum
   db_username: curriculum
   db_port: 3306
   service_dir: /usr/share/nginx/{{ service_name }}
   tasks:
    - name: SECRET PL0X
      include_vars: secret.yml

    - name: PLS INSTALL [epel-release]
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: INSTALL PHP 5.4 PL0X
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: NGINX GOD INSTALL PLZ
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install
    
    - name:  DOWNLOAD T3h INSTALLER
      become: yes
      get_url: 
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0777
        
    - name: Composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: CONFIGURE Teh NGINX
      become: yes
      copy: src=~/cit-360/ansible/web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name: CONFIGURE t3h vhost_conf
      become: yes
      template: src=~/cit-360/ansible/web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: REGISTUR php conf PL0X
      become: yes
      template: src=~/cit-360/ansible/web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: REGISTUR php_fpm_conf PL0X
      become: yes
      copy: src=~/cit-360/ansible/web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: NGINX GOD RESTART PL0X
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: RESTART T3H php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: DIRECTORY PATH FILE
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: PLZ UNZUP 
      become: yes
      unarchive: src=~/cit-360/ansible/web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: UPDATE t3H COMPOSER
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}
      ignore_errors: True     

    - name: READ WRITE PERMISSION PL0X
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777

    - name: GIVE GOD NGINX FULL ACCESS TO BRAZZERS
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx

    - name: TEMPLATE PL0X
      become: yes
      template: src=~/cit-360/ansible/web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
